### ISSUE TITLE
关于模型结构的一些细节

### ISSUE THREAD

**Issue by Breeze-Zero** [zhaoziheng/K-Space-Transformer#1]
您好，很感谢您的工作，给我带来很多启发，但我对您文章的内容还有些疑惑，希望能得到您的解答。
首先，请问下图(b)中的P(大写)是指的什么，单纯是不可学习的正弦/余弦位置编码吗？
以及请问是将位置编码与LR的输出，这两者计算cross-attention吗？
另外Encoder和Decoder每个Transformer block数量能否说明？
![image](https://user-images.githubusercontent.com/78247190/192082099-e7ce3ab9-c736-4cc1-b8b5-3c7d65434cc9.png)

**Comment by zhaoziheng** [comment]
你好，非常高兴你对我们工作感兴趣。关于你的问题：
1. P指的是坐标，我们使用二维的Position Encoding对其进行编码，也就是你说的正弦余弦函数，这是不可学习的
2. 是的
3. 我们默认Enc和LRD都是4层，HRD是6层

**Comment by Breeze-Zero** [comment]
感谢您百忙之中的回复
