### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by wujm7** [zhaoziheng/K-Space-Transformer#3]
作者您好：我想问一下 我想换一个256*256的数据去跑您的实验，但是换了以后出现如下报错；RuntimeError: CUDA error: device-side assert triggered。我如果切片成128*128的数据就不会报错，请问这是为什么呢，想向您请教该如何解决！谢谢！

**Comment by zhaoziheng** [comment]
Jia Mian你好。我们在实验的过程中没有尝试256分辨率，因为我们使用的RTX3090-24GB显存不足以负担计算开销。你说的这个报错可以告诉我具体出现在什么位置吗？我猜测也许是使用更高的分辨率出现了index越界。

**Comment by wujm7** [comment]
谢谢您！原来是这样。我也认为是分辨率过高Index越界了，那如果3090跑不了的话那可能就不太适合跑256的数据了。
错误是出现在这个位置：  File "D:\workspace\mriworkaspace\recommend_workspace\K-Space-Transformer-main\K-Space-Transformer-main\Ktransformer.py", line 101, in forward
    unsampled_value.append(Up_LR_k[i, :, :, :][unsampled_pos[i, :, :]])  # k [query_len, c]

**Comment by XiaoMengLiLiLi** [comment]
> 作者您好：我想问一下 我想换一个256_256的数据去跑您的实验，但是换了以后出现如下报错；RuntimeError: CUDA error: device-side assert triggered。我如果切片成128_128的数据就不会报错，请问这是为什么呢，想向您请教该如何解决！谢谢！

您好！请问您有复现K-Space Transformer这篇文章吗？我得到的解码后的预测低分辨率KSpace数据以及对应的低分辨率图像如图中第二列所示。请问，你当时有遇到这样的情况吗？这样的预测结果是正常的吗？
![image](https://github.com/zhaoziheng/K-Space-Transformer/assets/108074838/1709a05b-e522-4fd9-b57f-7cb386d4d8b2)
