### ISSUE TITLE
数据预处理问题

### ISSUE THREAD

**Issue by ZhengChen6** [zhaoziheng/K-Space-Transformer#4]
作者您好，我发现您的代码里load的npy文件，我下载的数据集是.h5文件，请问您能共享一下您将h5转换成npy的代码吗？另外，请问OASIS数据集中您使用的是OASIS-1还是OASIS-2还是......所有？谢谢！

**Comment by zhaoziheng** [comment]
代码已补充。我用的是OASIS-1中的T1W图像数据

**Comment by Nimisha-Pabbichetty** [comment]
Hi, could you share why you're specifically considering the 10th and 15th slices (after and before normalising respectively) in the .h5 file? Also is this number valid for the fastMRI dataset as well or is it just for the OASIS dataset?

Also how are you generating the undersampling masks?

**Comment by zhaoziheng** [comment]
1. I just choose these slice to visualize and check the preprocess procedures. You may change the slice indexes or totally ignore these codes if you want. 

2. We use the code in https://github.com/rmsouza01/CD-Deep-Cascade-MR-Reconstruction to generate sampling masks.

**Comment by Nimisha-Pabbichetty** [comment]
1) Ahh thank you for the response! Just to clarify, you use all the slices available in the .h5 file to train but only visualise 1 of them to make sure the preprocessing is happening as expected?
2) Could you share some instructions on how exactly you use the linked repository to generate the masks?
3) In the data preprocessing file, you also have a function for downsampling but I don't see it being called anywhere. Is it unnecessary?

**Comment by Nimisha-Pabbichetty** [comment]
Hi! What do you set the crop size to in your data_preprocess code?

**Comment by zhaoziheng** [comment]
Hi. For fastMRI knee dataset, I center-cropped the image to 320x320 before downsampling to 128x128.

**Comment by XiaoMengLiLiLi** [comment]
> 
您好！请问您有复现K-Space Transformer这篇文章吗？我得到的解码后的预测低分辨率KSpace数据以及对应的低分辨率图像如图中第二列所示。请问，你当时有遇到这样的情况吗？这样的预测结果是正常的吗？
![image](https://github.com/zhaoziheng/K-Space-Transformer/assets/108074838/5a5cda50-e23b-4575-b76d-e3e2e5250017)
