### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Nimisha-Pabbichetty** [zhaoziheng/K-Space-Transformer#5]
![image](https://user-images.githubusercontent.com/60477893/228956525-2f15882c-1df3-40cb-9aed-52cf1c887000.png)
Hi! We're trying to train the K-Space Transformer on the FastMRI brain dataset. As things stand using the data_preprocess code, we generated the .npy files. The HR data is 256 * 256 while the LR data is 128 * 128 (we call the downsample function and pass the HR data to it to get the LR data). Is this the wrong way to do it? Because the code seems to expect the HR data as 128 * 128 as well. But if that is the case, then what is the difference between the HR and LR .npy arrays? Does LR data become 64 * 64 then?

**Comment by zhaoziheng** [comment]
Hi. In all the experiments, we set the hr MRI images to 128 * 128, and thus the lr images are set to 64 * 64.

**Comment by XiaoMengLiLiLi** [comment]
> ![image](https://user-images.githubusercontent.com/60477893/228956525-2f15882c-1df3-40cb-9aed-52cf1c887000.png) Hi! We're trying to train the K-Space Transformer on the FastMRI brain dataset. As things stand using the data_preprocess code, we generated the .npy files. The HR data is 256 * 256 while the LR data is 128 * 128 (we call the downsample function and pass the HR data to it to get the LR data). Is this the wrong way to do it? Because the code seems to expect the HR data as 128 * 128 as well. But if that is the case, then what is the difference between the HR and LR .npy arrays? Does LR data become 64 * 64 then?

您好！请问您有复现K-Space Transformer这篇文章吗？我得到的解码后的预测低分辨率KSpace数据以及对应的低分辨率图像如图中第二列所示。请问，你当时有遇到这样的情况吗？这样的预测结果是正常的吗？
![image](https://github.com/zhaoziheng/K-Space-Transformer/assets/108074838/a01657ad-3478-487a-8ea0-44f24d8820d5)
