### ISSUE TITLE
Test Set Masks 

### ISSUE THREAD

**Issue by iamshan794** [zhaoziheng/K-Space-Transformer#6]
I was able to load the 30 different test mask numpy arrays provided in your shared gdrive. Could you please mention their sampling pattern and corresponding range of 'factor' values used to generate them?

**Comment by zhaoziheng** [comment]
Hi, Sorry for the late reply.

I name these files based on the rule:
1) Train/Test
2) OAS/fastMRI
3) 128 -- the resolution
4) Uniform/G_2D -- sampling according to a 1D uniform/2D gaussian distribution 
4) 0.x -- the sampling ratio, i.e. the 'factor'
5) center_x -- width of the fully-sampled central area
