### ISSUE TITLE
关于数据归一化

### ISSUE THREAD

**Issue by hathawayxxh** [zhaoziheng/K-Space-Transformer#8]
作者您好，关于kspace的数据处理和归一化方式，我看您代码中的做法是首先把k-space信号变换成图像，然后在image domain做(x-mean)/std的归一化操作。得到normalized image之后再变换回k-space，将这个k-space信号送到网络处理。
请问我的理解是否正确？
我在自己的实验中尝试了这种归一化方式，但是最后变换回的k-space信号范围大概在(-200, 200)之间，最后模型的重建精度也非常低。不确定是否因为kspace data的数值范围太大导致模型无法正常训练。请问您之前有没有遇到过这个问题？是否需要对kspace data做其他的归一化处理呢？

**Comment by zhaoziheng** [comment]
1. 是的，我是这么做归一化的，且在所有的实验中保持一致。
2. 所有的预处理操作都在data_preprocess.py中。
